#!/usr/bin/python                                            #正常运行脚本是python filename，加入这个运行脚本是执行“./filename”
#coding:utf-8

#monitoring and alert
import os

def filter_specific_word(filename,keyword=None):
  """提取文件报错行，写入新文件"""
	output=”error.log”
	with open(filename) as f:
		error_list=[line for line in f if keyword in line]
	if error_list:
		with open(output,’w’) as f:
			f.writelines(error_list)
		return filename
	else:
		return None

#only used in linux
#require email
def send_email(To,message,filename=”error.log”):
	command=”echo ‘%s’ | mail –s \”error report\” –a %s %s” % (message,filename,To)
	os.system(command)                                #发送邮件，包含内容和附件,%s表示显示变量，可以直接替换为文本字符串（%s删除，不需要形参）   
                                                          # %s这个整体表示传进来的参数是一个字符串
monitor_files=[注意相对路径和绝对路径]

if __name==”__main__”:
	os.system(“> error.log”)                                  #清空文件error.log
	for file in monitor_files:
		resulth=filter_specific_word(file,’ERROR’)
		if result:
			send_email(“lidaidi2@huawie.com”,result)
